on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gopiacr.azurecr.io
        username: ${{ secrets.acr_gopiacr_username }}
        password: ${{ secrets.acr_gopiacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t gopiacr.azurecr.io/forresterdemo:${{ github.sha }}
        docker push gopiacr.azurecr.io/forresterdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_forresterdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep forresterdemo0598 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace forresterdemo0598`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: forresterdemo0598
        container-registry-url: gopiacr.azurecr.io
        container-registry-username: ${{ secrets.acr_gopiacr_username }}
        container-registry-password: ${{ secrets.acr_gopiacr_password }}
        secret-name: forresterdemdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: forresterdemo0598
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          gopiacr.azurecr.io/forresterdemo:${{ github.sha }}
        imagepullsecrets: |
          forresterdemdockerauth